apiVersion: v1
kind: Pod
metadata:
  name: testbox
  namespace: default
spec:
  containers:
  - name: sh
    image: public.ecr.aws/docker/library/alpine:3.19
    command: ["sh","-c","sleep infinity"]
    # If your cluster needs to go via a proxy for DNS, leave as default.
  restartPolicy: Never
